name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.8

      - run: sudo apt-get update && sudo apt-get install -y libbtrfs-dev

      - run: make
