name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: go build -o octant-plugin-kubevirt main.go

      - uses: softprops/action-gh-release@v1
        with:
          files: octant-plugin-kubevirt
